### ISSUE TITLE
Y-axis alteration

### ISSUE THREAD

**Issue by chrispritting** [aroneklund/surviplot#1]
Hi, Aron,

I really like your survplot package and I have been using the package for awhile. I appreciate all of the work you put in to it!

For the y-axis, is there an "las" equivalent to rotate the numbers on the y-axis? I've tried multiple things but nothing has worked. 

I appreciate any advice!

**Comment by aroneklund** [comment]
Thanks for the nice comments!  You can add a "las" argument to surviplot, and it will get passed to the plotting function. E.g.
```
surv <- Surv(colon$time / 365, colon$status)
surviplot(surv ~ rx, data = colon)
surviplot(surv ~ rx, data = colon, las = 1)
```
Is this what you're after?

**Comment by chrispritting** [comment]
Hello, thanks for the response.

Unfortunately, “las” doesn’t work when I use it. It might be that I’m using the function “survplot” instead of “surviplot”.

Christopher Pritting
(201) 234-1252
________________________________

**Comment by chrispritting** [comment]
Is there another command other than "las"?

**Comment by chrispritting** [comment]
Hello again,

Is there a way to make the surviplot graphics like the survplot graphics? For example, I like survplot’s appearance of the counts appearing over the x axis. I also like the overall spacing of the numbers and axis titles. Otherwise, I’ll use survplot and live with the sideways y axis.

Christopher

Christopher Pritting
(201) 234-1252
________________________________
From: Christopher Pritting
Sent: Wednesday, July 14, 2021 8:19:55 PM
To: aroneklund/surviplot ***@***.***>
Subject: RE: [aroneklund/surviplot] Y-axis alteration (#1)


Is there another command other than “las”?

**Comment by aroneklund** [comment]
Hi. I am not familiar with the survplot graphics, but you can see some surviplot examples here: http://www.cbs.dtu.dk/~eklund/surviplot/

Just to check... have you tried using `par` to set the `las` value before creating your survplot? This often works with plotting functions that don't directly support a "las" argument.  I.e. something like:
```
par(las = 1)
survplot(...
```

**Comment by chrispritting** [comment]
This was what I able to do in survplot. Notice the x axis.

Also, I think the par(las =1) worked! I did it on my laptop but its on its last legs so I’ll have to confirm with my lap computer later on. Thank you!

[Image.png]

Christopher Pritting
(201) 234-1252
________________________________

**Comment by chrispritting** [comment]
Your suggestion worked, thank you!
